version: "3.9"
services:
  postgres:
    image: "postgres"
    restart: always
    environment:
      POSTGRES_PASSWORD: backend
      POSTGRES_USER: backend
      POSTGRES_DB: backend
    ports:
      - 5432:5432
  postgres_test:
    image: "postgres"
    restart: always
    environment:
      POSTGRES_PASSWORD: backend_test
      POSTGRES_USER: backend_test
      POSTGRES_DB: backend_test
    ports:
      - 5433:5432
